name: model
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies: 
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  rxdart: ^0.27.3

dev_dependencies: 
  build_runner: ^2.1.7 
  objectbox_generator: any