version: '3'
services:
  app:
    context: ../../
    build: .
    ports:
      - 14000:4000
    environment:
      - DB_TYPE=sqlite
      - DB_SQLITE_DAYABASE=/link-note/data/link-note.db
    volumes:
      - ./.local:/link-note/data