name: models
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies: 
  cloud_firestore: ^3.1.5 
  cloud_firestore_odm: ^1.0.0-dev.5
  json_annotation: ^4.4.0

dev_dependencies: 
  build_runner: ^2.1.7 
  cloud_firestore_odm_generator: ^1.0.0-dev.5
  json_serializable: ^6.1.3

